### ISSUE TITLE
Active task tab is unreadable

### ISSUE THREAD

**Issue by jamessan** [mellertson/Jira-Full-Dark-CSS-Theme#2]
It seems like something in the last update affected the highlighting of the active tab for sub-tasks.

![image](https://user-images.githubusercontent.com/112971/81241160-89bfa400-8fd7-11ea-8a1c-c750e5cd23d7.png)

The color and background are the same, so it's not possible to read the tab.

According to Firefox's inspector the active rule is 

```css
div.tabwrap.aui-tabs.horizontal-tabs > ul#issue-tabs > li.active-tab.active > a, .aui-tabs.horizontal-tabs > .tabs-menu > .menu-item.active-tab a::after {
	color: #CF613A;
	background: #CF613A;
}
```

**Comment by mellertson** [comment]
Good catch.  Out of the following two options, which do you think looks better?

## Option 1
![image](https://user-images.githubusercontent.com/1175253/81455128-1aff5980-9143-11ea-9f5e-99fd4bed2387.png)

## Option 2
![image](https://user-images.githubusercontent.com/1175253/81455143-28b4df00-9143-11ea-8eb9-937407fd6ab8.png)

**Comment by jamessan** [comment]
I guess I'd go with Option 1.

---
One other thing I noticed is that the input fields, when using "Text" mode rather than "Visual" mode are quite hard to read.

The background for the field is being colored due to this rule:

```css
div.field-group input, div.field-group select, div.field-group textarea, div.field-group div.CodeMirror {
	border: #808080 !important;
	background-color: #808080 !important;
}
```

However, when "Visual" editing is active it looks like this rule applies:

```css
.code.panel, .sprint-health-dashboard-item, .wiki-edit-toolbar, .filter-list > li:hover, .filter-list > li.hover, #content .aui-page-panel-nav .tabs.vertical a:focus, #content .aui-page-panel-nav .tabs.vertical a:hover, #content .aui-page-panel-nav .tabs.vertical .active a:focus, #content .aui-page-panel-nav .tabs.vertical .active a:hover, form.aui .jira-wikifield ~ .save-options.wiki-button-bar, .sd-rte-bar, .operations > li:focus, .operations > li:hover, .operations > li > .active, .aui-button:active, .aui-button.active, .ghx-detail-nav-menu, .aui-sidebar .aui-sidebar-footer, .aui-sidebar .aui-sidebar-footer > .aui-sidebar-toggle:focus, .aui-sidebar .aui-sidebar-footer > .aui-sidebar-settings-button, .aui-sidebar-submenu .aui-sidebar-footer > .aui-sidebar-settings-button, .aui-sidebar .aui-sidebar-footer > .aui-sidebar-toggle, .aui-sidebar-submenu .aui-sidebar-footer > .aui-sidebar-toggle, .aui-sidebar .aui-sidebar-footer > .aui-sidebar-settings-button:hover, .aui-sidebar-submenu .aui-sidebar-footer > .aui-sidebar-settings-button:hover, .aui-sidebar .aui-sidebar-footer > .aui-sidebar-toggle:hover, .aui-sidebar-submenu .aui-sidebar-footer > .aui-sidebar-toggle:hover, .aui-sidebar .aui-sidebar-footer > .aui-sidebar-settings-button:focus, .aui-sidebar-submenu .aui-sidebar-footer > .aui-sidebar-settings-button:focus, .aui-sidebar-submenu .aui-sidebar-footer > .aui-sidebar-toggle:focus, .aui-header .aui-button-split-more.active, .aui-button-subtle.aui-button:active, .aui-button-subtle.aui-button.active, .gadget .dashboard-item-content, .layout .column .placeholder, .layout .column.empty .empty-text, table.aui > caption, #dashboard > .tabs.vertical .active a, #dashboard > .tabs.vertical li.active, #dashboard > .tabs.vertical a:focus, #dashboard > .tabs.vertical a:hover, .aui-sidebar .aui-sidebar-wrapper, .aui-sidebar-submenu .aui-sidebar-wrapper, html:not(.webkit):not(.chrome), body:not(#jira):not(.has-footer-options) {
	background: #202020 !important;
}
```

![image](https://user-images.githubusercontent.com/112971/81476089-e2608e00-91dd-11ea-9395-fe60e36371f6.png)
